#!/bin/sh
DIR=$1
SCRIPT=$DIR/$2
\rm $SCRIPT 2> /dev/null

echo '#!/bin/sh' > $SCRIPT
echo 'LOG='$2'.log' >> $SCRIPT
echo 'cp -pf '$DIR/$2'.img '$DIR'/es.img' >> $SCRIPT
echo 'vformat '$DIR'/disk.img > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/disk.img '$DIR'/../../os/bootsect/es.ldr > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/disk.img '$DIR'/es.img > /dev/null 2>&1' >> $SCRIPT

case $2 in
    main)
	echo 'vcopy '$DIR'/disk.img '$DIR'/../main.elf > /dev/null 2>&1' >> $SCRIPT
	;;
    start)
	echo 'vcopy '$DIR'/disk.img '$DIR'/../server.elf > /dev/null 2>&1' >> $SCRIPT
	echo 'vcopy '$DIR'/disk.img '$DIR'/../client.elf > /dev/null 2>&1' >> $SCRIPT
	;;
    binder)
        echo 'vcopy '$DIR'/disk.img '$DIR'/../binder.elf > /dev/null 2>&1' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../binderClient.elf > /dev/null 2>&1' >> $SCRIPT
	;;
    upcallTest)
        echo 'vcopy '$DIR'/disk.img '$DIR'/../upcallTest.elf > /dev/null 2>&1' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../upcallTestClient.elf > /dev/null 2>&1' >> $SCRIPT
	;;
    location)
        echo 'vcopy '$DIR'/disk.img '$DIR'/../location.elf > /dev/null 2>&1' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../locationClient.elf > /dev/null 2>&1' >> $SCRIPT
	;;
    eventManager)
        echo 'vcopy '$DIR'/disk.img '$DIR'/../eventManager.elf > /dev/null 2>&1' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../eventManagerClient.elf > /dev/null 2>&1' >> $SCRIPT
	;;
    console)
        echo 'vcopy '$DIR'/disk.img '$DIR'/../eventManager.elf > /dev/null 2>&1' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../eventManagerClient.elf > /dev/null 2>&1' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../console.elf > /dev/null 2>&1' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../consoleClient.elf > /dev/null 2>&1' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img /usr/share/fonts/japanese/TrueType/sazanami-mincho.ttf > /dev/null 2>&1' >> $SCRIPT
	;;
esac

echo '' >> $SCRIPT
echo '# run QEMU on the background.' >> $SCRIPT
echo '(qemu -hda '$DIR'/disk.img -serial stdio -soundhw sb16 $QFLAGS | tee '$DIR'/$LOG 2>&1)' >> $SCRIPT
echo '' >> $SCRIPT

chmod u+x $SCRIPT

