#!/bin/sh
DIR=$1
SRC=$2
SCRIPT=$DIR/$3
\rm $SCRIPT 2> /dev/null

echo '#!/bin/sh' > $SCRIPT
echo 'vformat '$DIR'/fat32.img > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$DIR'/../os/bootsect/es.ldr > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$DIR'/es.img > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$DIR'/../cmd/squeak-3.7.1/squeak.elf > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$SRC'/../cmd/squeak-3.7.1/SqueakV3.sources > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$SRC'/../cmd/squeak-3.7.1/Squeak3.7-5989-full.changes > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$SRC'/../cmd/squeak-3.7.1/Squeak3.7-5989-full.image > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$DIR'/../esjs/esjs.elf > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$SRC'/../esjs/scripts/shell.js > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$SRC'/../esjs/scripts/echo.js > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$SRC'/../esjs/scripts/edit.js > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$SRC'/../esjs/scripts/cat.js > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$SRC'/../esjs/scripts/cd.js > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$SRC'/../esjs/scripts/ls.js > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$SRC'/../esjs/scripts/date.js > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$SRC'/../esjs/scripts/figure.js > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$SRC'/../esjs/scripts/clear.js > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$DIR'/../cmd/hello.elf > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$DIR'/../cmd/eventManager.elf > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img '$DIR'/../cmd/console.elf > /dev/null 2>&1' >> $SCRIPT
echo 'vcopy '$DIR'/fat32.img /usr/share/fonts/japanese/TrueType/sazanami-mincho.ttf > /dev/null 2>&1' >> $SCRIPT

echo '' >> $SCRIPT
echo 'echo usage: qemu -hda '$DIR'/fat32.img -serial stdio -soundhw sb16 -net nic,vlan=0 -net tap,vlan=0,ifname=tap0,script=/etc/qemu-ifup' >> $SCRIPT
chmod u+x $SCRIPT
