#!/bin/bash

# Check out the source code from Google Code
cd
mkdir es
cd es
mkdir trunk
svn checkout http://es-operating-system.googlecode.com/svn/trunk/ trunk

# Building development tools
mkdir local
cd local
CFLAGS=-g CXXFLAGS=-g ../trunk/configure
make
sudo make install

# Binutils
cd ..
mkdir src
cd src
wget ftp://ftp.gnu.org/gnu/binutils/binutils-2.18.tar.bz2
tar -jxvf binutils-2.18.tar.bz2
patch -p0 -d . < ../trunk/patches/binutils-2.18.patch
cd ..
mkdir opt
cd opt
mkdir binutils
cd binutils
../../src/binutils-2.18/configure --target=i386-pc-es --prefix=/opt/es
make
make install
export PATH=/opt/es/bin:$PATH

# GCC and Newlib
cd ../../src/
wget ftp://ftp.gnu.org/gnu/gcc/gcc-4.3.1/gcc-4.3.1.tar.bz2
tar -jxvf gcc-4.3.1.tar.bz2
patch -p0 -d . < ../trunk/patches/gcc-4.3.1.patch
wget ftp://sources.redhat.com/pub/newlib/newlib-1.16.0.tar.gz
tar -zxvf newlib-1.16.0.tar.gz
patch -p0 -d . < ../trunk/patches/newlib-1.16.0.patch
cd gcc-4.3.1
ln -s ../newlib-1.16.0/newlib .
ln -s ../newlib-1.16.0/libgloss .
cd ../../opt
mkdir gcc
cd gcc
../../src/gcc-4.3.1/configure --target=i386-pc-es --enable-threads --enable-languages=c,c++ --with-gnu-as --with-gnu-ld --with-newlib --with-gmp=/usr --with-mpfr=/usr --disable-shared --prefix=/opt/es
make
make install

# PCRE
cd ../../src/
wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-7.2.tar.bz2
tar -jxvf pcre-7.2.tar.bz2
patch -p0 -d . < ../trunk/patches/pcre-7.2.patch
cd ../opt
mkdir pcre
cd pcre
../../src/pcre-7.2/configure --prefix=/opt/es --disable-shared --enable-utf8 --enable-unicode-properties --host=i386-pc-es --target=i386-pc-es
make
make install

# FreeType 2
cd ../../src/
wget http://superb-east.dl.sourceforge.net/sourceforge/freetype/freetype-2.3.5.tar.bz2
tar -jxvf freetype-2.3.5.tar.bz2
patch -p0 -d . < ../trunk/patches/freetype-2.3.5.patch
cd ../opt
mkdir freetype
cd freetype
../../src/freetype-2.3.5/configure --prefix=/opt/es --host=i386-pc-es --target=i386-pc-es
make FTSYS_SRC=../../src/freetype-2.3.5/builds/unix/ftsystem.c
make install

# Expat
cd ../../src/
wget http://superb-west.dl.sourceforge.net/sourceforge/expat/expat-2.0.1.tar.gz
tar -zxvf expat-2.0.1.tar.gz
patch -p0 -d . < ../trunk/patches/expat-2.0.1.patch
cd ../opt
mkdir expat
cd expat
../../src/expat-2.0.1/configure --prefix=/opt/es --host=i386-pc-es --target=i386-pc-es
make
make installlib

# Fontconfig
cd ../../src/
wget http://fontconfig.org/release/fontconfig-2.4.2.tar.gz
tar -zxvf fontconfig-2.4.2.tar.gz
patch -p0 -d . < ../trunk/patches/fontconfig-2.4.2.patch
cd ../opt
mkdir fontconfig
cd fontconfig
../../src/fontconfig-2.4.2/configure --prefix=/opt/es --host=i386-pc-es --target=i386-pc-es --with-arch=i386-pc-es --with-expat-includes=/opt/es/include --with-expat-lib=/opt/es/lib --with-freetype-config=/opt/es/bin/freetype-config --with-default-fonts=/file/fonts --with-cache-dir=/file --with-confdir=/file
make
make install

# Cairo
cd ../../src/
wget http://cairographics.org/releases/cairo-1.4.10.tar.gz
tar -zxvf cairo-1.4.10.tar.gz
patch -p0 -d . < ../trunk/patches/cairo-1.4.10.patch
cd ../opt
mkdir cairo
cd cairo
../../src/cairo-1.4.10/configure --prefix=/opt/es --host=i386-pc-es --target=i386-pc-es --disable-png --disable-xlib --disable-ps --disable-svg FREETYPE_CFLAGS='-I/opt/es/include/freetype2 -I/opt/es/include' FREETYPE_LIBS='-L/opt/es/lib -lfreetype' FONTCONFIG_CFLAGS=-I/opt/es/include FONTCONFIG_LIBS='-L/opt/es/lib -lfontconfig'
make
make install

# ES operating system for PC
cd ../..
mkdir pc
cd pc
CFLAGS=-g CXXFLAGS=-g ../trunk/configure --prefix=/opt/es --host=i386-pc-es --target=i386-pc-es
make
make install

# Squeak port for ES
cd cmd
mkdir squeak-3.7.1
cd squeak-3.7.1
CFLAGS=-g CXXFLAGS=-g ../../../trunk/cmd/squeak-3.7.1/configure --prefix=/opt/es --host=i386-pc-es --target=i386-pc-es
make
cd ../../../trunk/cmd/squeak-3.7.1/
wget http://ftp.squeak.org/3.7/Squeak3.7-5989-full.zip
unzip Squeak3.7-5989-full.zip
wget http://ftp.squeak.org/3.7/SqueakV3.sources.gz
gunzip SqueakV3.sources.gz

# Run ES on QEMU
cd ../../../pc/init/
./es
qemu -hda fat32.img -serial stdio -soundhw sb16 -cdrom ../os/kernel/testsuite/isotest.iso
