/*
 * Copyright (c) 2006
 * Nintendo Co., Ltd.
 *  
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Nintendo makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 */

import "es/base/IInterface.idl";

[object, uuid(83a1dfd0-25dc-11db-9c02-0009bf000001)]
interface ICursor : IInterface
{
    int show();
    int hide();
    void move(int dx, int dy);
    void getPosition([out] int& x, [out] int& y);
    void setPosition(int x, int y);
    void setPattern([in] unsigned int data[32], [in] unsigned int mask[32],
                    unsigned short xHotSpot, unsigned short yHotSpot);
}
