/*
 * Copyright (c) 2006
 * Nintendo Co., Ltd.
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Nintendo makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 */

import "es/base/IInterface.idl";

/**
 * This interface provides methods for managing a cursor.
 */
[object, uuid(83a1dfd0-25dc-11db-9c02-0009bf000001)]
interface ICursor : IInterface
{
    /**
     * Shows this cursor.
     */
    int show();
    /**
     * Hides this cursor.
     */
    int hide();
    /**
     * Moves this cursor a specified distance.
     * @param dx the amount to move in x-direction from the current position.
     * @param dy the amount to move in y-direction from the current position.
     */
    void move(int dx, int dy);
    /**
     * Gets the position of this cursor.
     * @param dx the x-coordinate of this cursor.
     * @param dy the y-coordinate of this cursor.
     */
    void getPosition([out] int& x, [out] int& y);
    /**
     * Sets the position of this cursor.
     * @param dx the new x-coordinate of this cursor.
     * @param dy the new y-coordinate of this cursor.
     */
    void setPosition(int x, int y);
    /**
     * Sets the pattern of this cursor.
     * @param data 32x32 dots pattern of this cursor.
     * @param mask 32x32 mask pattern.
     * @param xHotSpot the positive offset of this cursor hotspot in x-direction.
     * The offset is measured from the left of this cursor.
     * @param yHotSpot the positive offset of this cursor hotspot in y-direction.
     * The offset is measured from the top of this cursor.
     */
    void setPattern([in] unsigned int data[32], [in] unsigned int mask[32],
                    unsigned short xHotSpot, unsigned short yHotSpot);
}

