/*
 * Copyright (c) 2006
 * Nintendo Co., Ltd.
 *  
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Nintendo makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 */

import "es/base/IInterface.idl";

[object, uuid(83a44e14-25dc-11db-9c02-0009bf000001)]
interface IDiskManagement : IInterface
{
    struct Geometry
    {
        unsigned int heads;
        unsigned int cylinders;
        unsigned int sectorsPerTrack;
        unsigned int bytesPerSector;
        long diskSize;
    };

    struct Partition
    {
        long startingOffset;
        long partitionLength;
        unsigned int hiddenSectors;
        unsigned byte partitionType;
        unsigned byte bootIndicator;
    };

    /** Initializes the disk partition table */
    int initialize();

    /** Gets information about the physical disk's geometry */
    int getGeometry([out] Geometry* geometry);

    /** Reads information about the partition on a disk */
    int getLayout([out] Partition* partition);

    /** Writes information about the partition on a disk */
    int setLayout([in, out] Partition* partition);
}
