/*
 * Copyright (c) 2006
 * Nintendo Co., Ltd.
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Nintendo makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 */

import "es/base/IStream.idl";

/**
 * This interface represents partitions in a disk.
 */
[object, uuid(e4a2e00a-47b4-11db-9c02-0009bf000001)]
interface IPartition : IInterface
{
    /**
     * Initialize MBR of the mounted disk.
     */
    int initialize();

    /**
     * Registers partitions in the specified disk to this partition object.
     * @param disk the disk divided into partitions.
     */
    int mount(IStream* disk);
    /**
     * Removes all entries of partitions from this partition object.
     */
    int unmount();
}
