/*
 * Copyright (c) 2006, 2007
 * Nintendo Co., Ltd.
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Nintendo makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 */

#ifndef NINTENDO_ES_DEVICE_IPARTITION_IDL_INCLUDED
#define NINTENDO_ES_DEVICE_IPARTITION_IDL_INCLUDED

#include "es/base/IStream.idl"

module es
{
    /**
     * This interface represents partitions in a disk.
     */
    interface IPartition : IInterface
    {
        #pragma ID IPartition = "DCE:e4a2e00a-47b4-11db-9c02-0009bf000001";
        /**
         * Initialize MBR of the mounted disk.
         */
        long initialize();

        /**
         * Registers partitions in the specified disk to this partition object.
         * @param disk the disk divided into partitions.
         */
        long mount(in IStream disk);
        /**
         * Removes all entries of partitions from this partition object.
         */
        long unmount();
    };
};

#endif // NINTENDO_ES_DEVICE_IPARTITION_IDL_INCLUDED

