/*
 * Copyright 2008, 2009 Google Inc.
 * Copyright 2006, 2007 Nintendo Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef NINTENDO_ES_BASE_IFILE_IDL_INCLUDED
#define NINTENDO_ES_BASE_IFILE_IDL_INCLUDED

#include "es/base/IStream.idl"
#include "es/base/IPageable.idl"

module es
{
    /** This interface provides methods for handling files and directories.
     */
    interface File
    {
        const long ReadOnly = 0x01;
        const long Hidden = 0x02;
        const long System = 0x04;
        const long Directory = 0x10;
        const long Archive = 0x20;

        /** The attributes of this file.
         * @param attributes    A unsigned int value from which to obtain the attributes
         *                      of this file.
         */
        attribute unsigned long attributes;

        /** The time this file was created.
         * @param time      A long value from which to obtain the creation
         *                  time of this file.
         */
        attribute long long creationTime;

        /** The time this file was last read.
         * @param time      A long value from which to obtain the last
         *                  read time of this file.
         */
        attribute long long lastAccessTime;

        /** The time this file was last modified.
         * @param time      A long value from which to obtain the last
         *                  modified time of this file.
         */
        attribute long long lastWriteTime;

        /** Test whether this file can be read.
         */
        boolean canRead();

        /** Test whether this file can be modified.
         */
        boolean canWrite();

        /** Tests whether this file is a directory.
         * @return          true if and only if this file is a directory; false otherwise.
         */
        boolean isDirectory();

        /** Tests whether this file is a normal file.
         * @return          true if and only if this file is a normal file; false otherwise.
         */
        boolean isFile();

        /** Tests whether this file is a hidden file.
         * @return          true if and only if this file is a hidden file; false otherwise.
         */
        boolean isHidden();

        /** The string representation of this file.
         */
        readonly attribute string name;

        /** The unique IPageable interface associated with this file.
         */
        readonly attribute Pageable pageable;

        /** The length of this file.
         */
        readonly attribute long long size;

        /** The unique IStream interface associated with this file.
         */
        readonly attribute Stream stream;
    };
};

#endif // NINTENDO_ES_BASE_IFILE_IDL_INCLUDED

