/*
 * Copyright (c) 2006
 * Nintendo Co., Ltd.
 *  
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Nintendo makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 */

import "es/base/IInterface.idl";

/** This interface represents a naming context, which consists of a set
 * of name-to-object bindings. It contains methods for examining and
 * updating these bindings.
 */
[object, uuid(33f5e13e-25dc-11db-9c02-0009bf000001)]
interface IBinding : IInterface
{
    /** Retrieves the object bound to this binding.
     * @return          The object bound.
     */
    IInterface* getObject();

    /** Sets the object associated with this binding.
     * @return          The object to set.
     */
    int setObject(IInterface* element);

    /** Retrieves the string representation of this binding.
     * @return          The string representation of this binding.
     */
    int getName([out, size_is(len)] char* name, unsigned int len);
}
