#!/bin/sh
DIR=$1
SRC=$2
SCRIPT=$DIR/$3
\rm $SCRIPT 2> /dev/null

echo '#!/bin/sh' > $SCRIPT
echo 'LOG='$3'.log' >> $SCRIPT
echo 'cp -pf '$DIR/$3'.img '$DIR'/es.img' >> $SCRIPT
echo 'vformat '$DIR'/disk.img > /dev/null' >> $SCRIPT
echo 'vcopy '$DIR'/disk.img '$DIR'/../../os/bootsect/es.ldr > /dev/null' >> $SCRIPT
echo 'vcopy '$DIR'/disk.img '$DIR'/es.img > /dev/null' >> $SCRIPT

case $3 in
    main)
	echo 'vcopy '$DIR'/disk.img '$DIR'/../main.elf > /dev/null' >> $SCRIPT
	;;
    start)
	echo 'vcopy '$DIR'/disk.img '$DIR'/../server.elf > /dev/null' >> $SCRIPT
	echo 'vcopy '$DIR'/disk.img '$DIR'/../client.elf > /dev/null' >> $SCRIPT
	;;
    binder)
        echo 'vcopy '$DIR'/disk.img '$DIR'/../binder.elf > /dev/null' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../binderClient.elf > /dev/null' >> $SCRIPT
	;;
    upcallTest)
        echo 'vcopy '$DIR'/disk.img '$DIR'/../upcallTest.elf > /dev/null' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../upcallTestClient.elf > /dev/null' >> $SCRIPT
	;;
    location)
        echo 'vcopy '$DIR'/disk.img '$DIR'/../location.elf > /dev/null' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../locationClient.elf > /dev/null' >> $SCRIPT
	;;
    eventManager)
        echo 'vcopy '$DIR'/disk.img '$DIR'/../eventManager.elf > /dev/null' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../eventManagerClient.elf > /dev/null' >> $SCRIPT
	;;
    console)
        echo 'vcopy '$DIR'/disk.img '$DIR'/../eventManager.elf > /dev/null' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../eventManagerClient.elf > /dev/null' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../console.elf > /dev/null' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img '$DIR'/../consoleClient.elf > /dev/null' >> $SCRIPT
        echo 'vcopy '$DIR'/disk.img /usr/share/fonts/japanese/TrueType/sazanami-mincho.ttf fonts/ > /dev/null' >> $SCRIPT
	;;
    newlib)
        echo 'vcopy '$DIR'/disk.img '$DIR'/../newlib.elf > /dev/null' >> $SCRIPT
	echo 'vcopy '$DIR'/disk.img '$SRC'/../../esjs/scripts/cat.js > /dev/null' >> $SCRIPT
	;;
esac

echo '' >> $SCRIPT
echo '# run QEMU on the background.' >> $SCRIPT
echo '(qemu -hda '$DIR'/disk.img -serial stdio -soundhw sb16 $QFLAGS | tee '$DIR'/$LOG)' >> $SCRIPT
echo '' >> $SCRIPT

chmod u+x $SCRIPT

