/*
 * Copyright (c) 2006
 * Nintendo Co., Ltd.
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Nintendo makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 */

import "es/base/IInterface.idl";

/** This interface provides a callback mechanism.
 */
[object, uuid(03230cd6-25db-11db-9c02-0009bf000001)]
interface ICallback : IInterface
{
    /**
     * This method is called as a callback.
     * @param result the result value.
     */
    int invoke(int result);
}
