/*
 * Copyright (c) 2006
 * Nintendo Co., Ltd.
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Nintendo makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 */

import "es/base/IInterface.idl";

/**
 * This interface provides methods for managing interface reflection data.
 * @since 0.0.3
 */
[object, uuid(3e34081e-4928-11db-9c02-0009bf000001)]
interface IInterfaceStore : IInterface
{
    /**
     * Registers the interface reflection data in this interface store.
     * @param data  the interface reflection data.
     * @param length    the size of data.
     */
    void add([in, size_is(length)] void* data, int length);
    /**
     * Removes the specified interface reflection data in this interface store.
     * @param       riid the interface ID.
     */
    void remove([in] uuid& riid);
}
