/*
 * Copyright (c) 2006
 * Nintendo Co., Ltd.
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Nintendo makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 */

/** This interface is the root of the component interface hierarchy.
 */
[object, uuid(d73c48f0-37e9-11db-9c02-0009bf000001)]
interface IInterface
{
    /** Determines if an interface can be used with this object.
     * @param riid          UUID of the interface to be queried.
     * @param objectPtr     pointer to a buffer that receives a pointer
     *                      to the object.
     */
    boolean queryInterface([in] uuid& riid, [out, iid_is(riid)] void** objectPtr);

    /** Increments the reference count of this object.
     */
    unsigned int addRef();

    /** Decrements the reference count of this object.
     * @return              Zero if this object is no longer available.
     */
    unsigned int release();
}
