/*
 * Copyright (c) 2006
 * Nintendo Co., Ltd.
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Nintendo makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 */

import "es/base/IInterface.idl";

/**
 * This interface provides methods for managing pageable objects.
 */
[object, uuid(0327e274-25db-11db-9c02-0009bf000001)]
interface IPageable : IInterface
{
    /** Gets the physical page address at the specified offset of this pageable object.
     * @param offset the offset of this pageable object.
     * @return      Physical page address.
     */
    unsigned long get(long offset);

    /** Releases the page at the specified offset of this pageable object.
     * @param offset the offset of this pageable object.
     * @param pte the page table entry.
     */
    void put(long offset, unsigned long pte);

    /** Gets the size of this pageable object.
     * @return the size of this pageable object.
     */
    long getSize();

    /** Resizes this pageable object.
     * @param size the new size of this pageable object.
     */
    void setSize(long size);
}
