/*
 * Copyright (c) 2007
 * Nintendo Co., Ltd.
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Nintendo makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 */

#ifndef NINTENDO_ES_BASE_ISELECTABLE_IDL_INCLUDED
#define NINTENDO_ES_BASE_ISELECTABLE_IDL_INCLUDED

#include "es/base/IMonitor.idl"

module es
{
    /** A selectable object notifies the registered monitor objects
     * when its state is changed.
     */
    interface ISelectable : IInterface
    {
        #pragma ID ISelectable = "DCE:4714271e-d101-11db-9c02-0009bf000001";

        /**
         * Registers a monitor object to this selectable object.
         * @param selector a monitor object.
         */
        long add(in IMonitor selector);
        /**
         * Unregisters a monitor object from this selectable object.
         * @param selector a monitor object.
         */
        long remove(in IMonitor selector);
    };
};

#endif // NINTENDO_ES_BASE_ISELECTABLE_IDL_INCLUDED

