/*
 * Copyright (c) 2007
 * Nintendo Co., Ltd.
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Nintendo makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 */

import "es/base/IMonitor.idl";

/** A selectable object notifies the registered monitor objects
 * when its state is changed.
 */
[object, uuid(4714271e-d101-11db-9c02-0009bf000001)]
interface ISelectable : IInterface
{
    /**
     * Registers a monitor object to this selectable object.
     * @param selector a monitor object.
     */
    int add(IMonitor* selector);
    /**
     * Unregisters a monitor object from this selectable object.
     * @param selector a monitor object.
     */
    int remove(IMonitor* selector);
}
