/*
 * Copyright (c) 2006, 2007
 * Nintendo Co., Ltd.
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Nintendo makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 */

#ifndef NINTENDO_ILOCATION_IDL_INCLUDED
#define NINTENDO_ILOCATION_IDL_INCLUDED

#include "es/base/IInterface.idl"

module es
{
    struct Point
    {
        long x;
        long y;
    };

    /**
     * This interface provides a location service.
     */
    interface ILocation : IInterface
    {
        #pragma ID ILocation = "DCE:113772a7-bf4a-4c91-b4cc-50514cf3b4f0";

        void set(in Point point);
        void get(out Point point);
        void move(in Point direction);

        attribute string name;
    };
};

#endif // NINTENDO_ILOCATION_IDL_INCLUDED
